#!/usr/bin/env zsh

sum=0
enabled=true
grep -oE '(do\(\))|(don'\''t\(\))|mul\([0-9]{1,3},[0-9]{1,3}\)' $1 |
while read -r line; do
	if [[ "$line" == "do()" ]];then
		enabled=true
	elif [[ "$line" == "don't()" ]];then
		enabled=false
	elif [[ "$line" =~ "mul\(([0-9]{1,3}),([0-9]{1,3})\)" ]] && $enabled; then
		(( sum+=${match[1]} * ${match[2]} ))
	fi
done
echo "$sum"
